export const ADD_PIZZA_TO_CART = "ADD_PIZZA_TO_CART";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";
export const PLUS_PIZZA_TO_CART = "PLUS_PIZZA_TO_CART";
export const MINUS_PIZZA_TO_CART = "MINUS_PIZZA_TO_CART";
export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
